### ISSUE TITLE
macOSでIME ON時にスペースを押しても変換候補が表示されない

### ISSUE THREAD

**Issue by ikegami-yukino** [shogo82148/AjaxIME#1]
macOSでIME ON時に文字を入力しアルファベットがひらがなに変換されるものの
スペースを押しても変換候補が表示されなかったので報告いたします。
ちなみにかなモードではなく英数モードでの入力です。

https://shogo82148.github.io/AjaxIME/

実行環境は下記のとおりです:
- macOS バージョン: 14.2.1
- Google Chrome バージョン: 123.0.6312.59
- Safari バージョン: 17.2.1 

よろしくお願いいたします。

**Comment by shogo82148** [comment]
#3 で暫定的に対応しました。
辞書に https://github.com/ikegami-yukino/mecab-as-kkc を利用しています。ありがとうございます。
